FROM python:3.10-slim
RUN apt-get update && apt-get install -y gcc build-essential tzdata
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple